[2024-09-21T10:09:56.068+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: dag_saver_v01.create_table_vk manual__2024-09-21T10:09:53.579601+00:00 [queued]>
[2024-09-21T10:09:56.074+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: dag_saver_v01.create_table_vk manual__2024-09-21T10:09:53.579601+00:00 [queued]>
[2024-09-21T10:09:56.075+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2024-09-21T10:09:56.075+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2024-09-21T10:09:56.075+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2024-09-21T10:09:56.082+0000] {taskinstance.py:1304} INFO - Executing <Task(PostgresOperator): create_table_vk> on 2024-09-21 10:09:53.579601+00:00
[2024-09-21T10:09:56.087+0000] {standard_task_runner.py:55} INFO - Started process 3185 to run task
[2024-09-21T10:09:56.091+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dag_saver_v01', 'create_table_vk', 'manual__2024-09-21T10:09:53.579601+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/dag_saver.py', '--cfg-path', '/tmp/tmp6cztur4a']
[2024-09-21T10:09:56.092+0000] {standard_task_runner.py:83} INFO - Job 3: Subtask create_table_vk
[2024-09-21T10:09:56.145+0000] {task_command.py:389} INFO - Running <TaskInstance: dag_saver_v01.create_table_vk manual__2024-09-21T10:09:53.579601+00:00 [running]> on host 16da3808dee2
[2024-09-21T10:09:56.195+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=<NAME>
AIRFLOW_CTX_DAG_ID=dag_saver_v01
AIRFLOW_CTX_TASK_ID=create_table_vk
AIRFLOW_CTX_EXECUTION_DATE=2024-09-21T10:09:53.579601+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-09-21T10:09:53.579601+00:00
[2024-09-21T10:09:56.195+0000] {sql.py:253} INFO - Executing: 
        
        
        
[2024-09-21T10:09:56.201+0000] {base.py:73} INFO - Using connection ID 'postgres_default' for task execution.
[2024-09-21T10:09:56.347+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 261, in execute
    return_last=self.return_last,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 329, in run
    raise ValueError("List of SQL statements is empty")
ValueError: List of SQL statements is empty
[2024-09-21T10:09:56.354+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_saver_v01, task_id=create_table_vk, execution_date=20240921T100953, start_date=20240921T100956, end_date=20240921T100956
[2024-09-21T10:09:56.362+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 3 for task create_table_vk (List of SQL statements is empty; 3185)
[2024-09-21T10:09:56.398+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2024-09-21T10:09:56.414+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
