[2024-09-21T10:57:00.399+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: dag_saver_v01.insert_data manual__2024-09-21T10:56:56.625966+00:00 [queued]>
[2024-09-21T10:57:00.408+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: dag_saver_v01.insert_data manual__2024-09-21T10:56:56.625966+00:00 [queued]>
[2024-09-21T10:57:00.409+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2024-09-21T10:57:00.409+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2024-09-21T10:57:00.409+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2024-09-21T10:57:00.420+0000] {taskinstance.py:1304} INFO - Executing <Task(PostgresOperator): insert_data> on 2024-09-21 10:56:56.625966+00:00
[2024-09-21T10:57:00.424+0000] {standard_task_runner.py:55} INFO - Started process 6909 to run task
[2024-09-21T10:57:00.437+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dag_saver_v01', 'insert_data', 'manual__2024-09-21T10:56:56.625966+00:00', '--job-id', '46', '--raw', '--subdir', 'DAGS_FOLDER/dag_saver.py', '--cfg-path', '/tmp/tmpleik4ugu']
[2024-09-21T10:57:00.438+0000] {standard_task_runner.py:83} INFO - Job 46: Subtask insert_data
[2024-09-21T10:57:00.520+0000] {task_command.py:389} INFO - Running <TaskInstance: dag_saver_v01.insert_data manual__2024-09-21T10:56:56.625966+00:00 [running]> on host 16da3808dee2
[2024-09-21T10:57:00.567+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=<NAME>
AIRFLOW_CTX_DAG_ID=dag_saver_v01
AIRFLOW_CTX_TASK_ID=insert_data
AIRFLOW_CTX_EXECUTION_DATE=2024-09-21T10:56:56.625966+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-09-21T10:56:56.625966+00:00
[2024-09-21T10:57:00.569+0000] {sql.py:253} INFO - Executing: 
            insert into vk_group_posts (vk_group_link, vk_post_id, vk_post_text, vk_post_comments) 
                values (
                    'sportcast.online',
                    '{ti.xcom_pull(task_ids="fetch_vk_data", key="vk_post_id")}',
                    '{ti.xcom_pull(task_ids="fetch_vk_data", key="text_post")}',
                    '{ti.xcom_pull(task_ids="fetch_vk_data", key="comments_post")}'
                );
        
[2024-09-21T10:57:00.575+0000] {base.py:73} INFO - Using connection ID 'postgres_default' for task execution.
[2024-09-21T10:57:00.704+0000] {base.py:73} INFO - Using connection ID 'postgres_default' for task execution.
[2024-09-21T10:57:00.710+0000] {sql.py:364} INFO - Running statement: 
            insert into vk_group_posts (vk_group_link, vk_post_id, vk_post_text, vk_post_comments) 
                values (
                    'sportcast.online',
                    '{ti.xcom_pull(task_ids="fetch_vk_data", key="vk_post_id")}',
                    '{ti.xcom_pull(task_ids="fetch_vk_data", key="text_post")}',
                    '{ti.xcom_pull(task_ids="fetch_vk_data", key="comments_post")}'
                );
        , parameters: None
[2024-09-21T10:57:00.711+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 261, in execute
    return_last=self.return_last,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 338, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 369, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.InvalidTextRepresentation: invalid input syntax for type integer: "{ti.xcom_pull(task_ids="fetch_vk_data", key="vk_post_id")}"
LINE 5:                     '{ti.xcom_pull(task_ids="fetch_vk_data",...
                            ^

[2024-09-21T10:57:00.717+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_saver_v01, task_id=insert_data, execution_date=20240921T105656, start_date=20240921T105700, end_date=20240921T105700
[2024-09-21T10:57:00.723+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 46 for task insert_data (invalid input syntax for type integer: "{ti.xcom_pull(task_ids="fetch_vk_data", key="vk_post_id")}"
LINE 5:                     '{ti.xcom_pull(task_ids="fetch_vk_data",...
                            ^
; 6909)
[2024-09-21T10:57:00.737+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2024-09-21T10:57:00.748+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
